# Generated by Django 3.2.12 on 2022-04-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_description', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('order_date', models.DateTimeField()),
                ('receiver', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=225)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='productinfo.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('pm_id', models.AutoField(primary_key=True, serialize=False)),
                ('pm_name', models.CharField(max_length=45, unique=True)),
                ('pm_description', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Method',
            fields=[
                ('sm_id', models.AutoField(primary_key=True, serialize=False)),
                ('sm_name', models.CharField(max_length=45, unique=True)),
                ('sm_description', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_carts', to='productinfo.customer')),
                ('pm_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_carts', to='productinfo.payment_method')),
                ('sm_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_carts', to='productinfo.shipping_method')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=225, unique=True)),
                ('product_price', models.FloatField()),
                ('stock_num', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='productinfo.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('oitem_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_products', to='productinfo.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_products', to='productinfo.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='productinfo.payment_method'),
        ),
        migrations.AddField(
            model_name='order',
            name='sm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='productinfo.shipping_method'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='productinfo.payment_method'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='productinfo.shipping_method'),
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('ci_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='productinfo.shopping_cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='productinfo.product')),
            ],
        ),
    ]
