# Generated by Django 3.2.12 on 2022-04-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productinfo', '0002_auto_20220414_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_item',
            options={'ordering': ['cart_id', 'product_id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date', 'order_id']},
        ),
        migrations.AlterModelOptions(
            name='order_product',
            options={'ordering': ['oitem_id']},
        ),
        migrations.AlterModelOptions(
            name='payment_method',
            options={'ordering': ['pm_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id']},
        ),
        migrations.AlterModelOptions(
            name='shipping_method',
            options={'ordering': ['sm_name']},
        ),
        migrations.AlterModelOptions(
            name='shopping_cart',
            options={'ordering': ['cart_id']},
        ),
        migrations.AddConstraint(
            model_name='cart_item',
            constraint=models.UniqueConstraint(fields=('ci_id', 'cart_id', 'product_id'), name='unique_cartitem'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('customer_id', 'username', 'email', 'last_name', 'first_name', 'disambiguator'), name='unique_customer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_id',), name='unique_order'),
        ),
        migrations.AddConstraint(
            model_name='order_product',
            constraint=models.UniqueConstraint(fields=('oitem_id', 'order_id', 'product_id'), name='unique_orderproduct'),
        ),
        migrations.AddConstraint(
            model_name='payment_method',
            constraint=models.UniqueConstraint(fields=('pm_name',), name='unique_pm'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_name',), name='unique_product'),
        ),
        migrations.AddConstraint(
            model_name='shipping_method',
            constraint=models.UniqueConstraint(fields=('sm_name',), name='unique_sm'),
        ),
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('cart_id', 'customer_id'), name='unique_shoppingcart'),
        ),
    ]
