# Generated by Django 3.2.12 on 2022-04-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productinfo', '0003_auto_20220420_2225'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopping_cart',
            name='unique_shoppingcart',
        ),
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('customer_id',), name='unique_shoppingcart'),
        ),
    ]
