# Generated by Django 3.2.12 on 2022-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productinfo', '0004_auto_20220421_0428'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart_item',
            name='unique_cartitem',
        ),
        migrations.AddConstraint(
            model_name='cart_item',
            constraint=models.UniqueConstraint(fields=('cart_id', 'product_id'), name='unique_cartitem'),
        ),
    ]
