# Generated by Django 3.2.12 on 2022-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productinfo', '0005_auto_20220421_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(max_length=225),
        ),
    ]
